apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-loader
spec:
  selector:
    matchLabels:
      app: influxdb-loader
  template:
    metadata:
      labels:
        app: influxdb-loader
    spec:
      containers:
        - name: influxdb-loader
          image: waggle/beehive-influxdb-loader
          ports:
            - name: metrics
              containerPort: 8080
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5671"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: influxdb-loader-auth
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-loader-auth
                  key: password
            - name: RABBITMQ_CACERTFILE
              value: "/etc/credentials/cacert.pem"
            - name: INFLUXDB_URL
              value: "http://influxdb:8086"
            - name: INFLUXDB_BUCKET
              value: "waggle"
            - name: INFLUXDB_ORG
              value: "waggle"
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-loader-influxdb-token
                  key: token
          volumeMounts:
            - name: credentials
              mountPath: "/etc/credentials"
              readOnly: true
      volumes:
        - name: credentials
          secret:
            name: influxdb-loader-credentials
