apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: rabbitmq
secretGenerator:
  - name: rabbitmq-config
    files:
      - "config/enabled_plugins"
      - "config/rabbitmq.conf"
      - "config/definitions.json"
  - name: rabbitmq-credentials
    files:
      - "credentials/cacert.pem"
      - "credentials/cert.pem"
      - "credentials/key.pem"
configMapGenerator:
  - name: rabbitmq-env
    literals:
      - "sync_url=http://beehive-nodes-service/sync"
resources:
  - service.yaml
  - statefulset.yaml
