apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: rabbitmq-config
    files:
      - "config/enabled_plugins"
      - "config/rabbitmq.conf"
      - "config/definitions.json"
configMapGenerator:
  - name: rabbitmq-env
    literals:
      - "sync_url=http://beehive-nodes-service/sync"
resources:
  - service.yaml
  - statefulset.yaml
