apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: LoadBalancer
  ports:
    - name: amqps
      port: 5671
      targetPort: amqps
    - name: https
      port: 15671
      targetPort: https
