apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: LoadBalancer
  ports:
    - name: amqps
      port: 49191
      targetPort: amqps
    - name: http
      port: 15672
      targetPort: http
