apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  selector: {}
  template:
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.10.5-management-alpine
        volumeMounts:
          - name: config
            mountPath: /etc/rabbitmq
            readOnly: true
          - name: credentials
            mountPath: "/etc/credentials"
            readOnly: true
          - name: data
            mountPath: /var/lib/rabbitmq
        ports:
        - name: amqps
          containerPort: 5671
        - name: amqp
          containerPort: 5672
        - name: https
          containerPort: 15671
        - name: http
          containerPort: 15672
        livenessProbe:
          exec:
            command: ["/bin/sh", "-ec", "rabbitmq-diagnostics -q ping"]
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command: ["/bin/sh", "-ec", "rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms"]
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 10
      - name: sidecar
        image: busybox
        command: ["sh", "-c", "while [ true ] ; do until wget ${sync_url} -O - -q ; do echo could not reach ${sync_url} ... ; sleep 3s ; done ; echo next round in 30 minutes... ; sleep 30m ; done"]
        envFrom:
          - configMapRef:
              name: rabbitmq-env
      volumes:
        - name: config
          secret:
            secretName: rabbitmq-config
        - name: credentials
          secret:
            secretName: rabbitmq-credentials
        - name: data
          persistentVolumeClaim:
            claimName: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
