apiVersion: v1
kind: Service
metadata:
  name: beehive-influxdb
  labels:
    app: beehive-influxdb
spec:
  ports:
    - name: beehive-influxdb
      port: 8086
      targetPort: influxdb
  selector:
    app: beehive-influxdb
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: beehive-influxdb
  name: beehive-influxdb
spec:
  serviceName: beehive-influxdb
  selector:
    matchLabels:
      app: beehive-influxdb
  template:
    metadata:
      labels:
        app: beehive-influxdb
    spec:
      containers:
        - image: influxdb:2.7.0
          name: beehive-influxdb
          ports:
            - containerPort: 8086
              name: influxdb
          env:
            - name: "INFLUXD_BOLT_PATH"
              value: "/var/lib/influxdb2-local/influxd.bolt"
            - name: "INFLUXD_ENGINE_PATH"
              value: "/var/lib/influxdb2-local/engine"
            - name: "INFLUX_CONFIGS_PATH"
              value: "/var/lib/influxdb2-local/configs"
            - name: INFLUXD_LOG_LEVEL
              value: "debug"
            - name: INFLUXD_QUERY_CONCURRENCY
              value: "25"
            - name: INFLUXD_QUERY_QUEUE_SIZE
              value: "25"
          volumeMounts:
            - mountPath: "/var/lib/influxdb2"
              name: data
            - mountPath: "/var/lib/influxdb2-local"
              name: data-local
            - mountPath: "/backup"
              name: backup
          resources:
            requests:
              cpu: 16000m
              memory: 32Gi
            limits:
              memory: 32Gi
          readinessProbe:
            httpGet:
              path: /health
              port: influxdb
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - "influx"
                - "query"
                - 'from(bucket: "_monitoring") |> range(start: -10s) |> count()'
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
      volumes:
        # NOTE(sean) Yes... we have a data and data-local PVC. This was a hack to migrate data from the
        # original ceph volume (data) to the local ssd volume (data-local) in production. In the future,
        # we should clean this up.
        - name: data
          persistentVolumeClaim:
            claimName: influxdb-data
        - name: backup
          persistentVolumeClaim:
            claimName: influxdb-backup
        - name: data-local
          persistentVolumeClaim:
            claimName: influxdb-data-local
