apiVersion: v1
kind: Service
metadata:
  name: beehive-influxdb
  labels:
    app: beehive-influxdb
spec:
  ports:
    - name: beehive-influxdb
      port: 8086
      targetPort: influxdb
  selector:
    app: beehive-influxdb
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: beehive-influxdb
  name: beehive-influxdb
spec:
  selector:
    matchLabels:
      app: beehive-influxdb
  template:
    metadata:
      labels:
        app: beehive-influxdb
    spec:
      containers:
        - image: influxdb:2.7.0
          name: beehive-influxdb
          ports:
            - containerPort: 8086
              name: influxdb
          env:
            - name: "INFLUXD_BOLT_PATH"
              value: "/var/lib/influxdb2-local/influxd.bolt"
            - name: "INFLUXD_ENGINE_PATH"
              value: "/var/lib/influxdb2-local/engine"
            - name: "INFLUX_CONFIGS_PATH"
              value: "/var/lib/influxdb2-local/configs"
          volumeMounts:
            - mountPath: "/var/lib/influxdb2"
              name: data
            - mountPath: "/var/lib/influxdb2-local"
              name: data-local
            - mountPath: "/backup"
              name: backup
          resources:
            requests:
              cpu: 8000m
              memory: 32Gi
            limits:
              memory: 32Gi
          livenessProbe:
            exec:
              command:
                - "influx"
                - "query"
                - 'from(bucket: "_monitoring") |> range(start: -10s) |> count()'
            initialDelaySeconds: 60
            periodSeconds: 60
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: influxdb-data
        - name: backup
          persistentVolumeClaim:
            claimName: influxdb-backup
        - name: data-local
          persistentVolumeClaim:
            claimName: influxdb-data-local
